name: myproject

services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - "54327:5432"
    environment:
      POSTGRES_USER: supakon
      POSTGRES_PASSWORD: ppap1190
      POSTGRES_DB: supakon
    volumes:
      - ./data/data:/var/lib/postgresql/data

  admin:
    image: dpage/pgadmin4
    container_name: 69-s2-admin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  app:
    image: prawee/strapi
    container_name: 69-s2-app
    restart: unless-stopped
    ports:
      - "9092:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: supakon
      DATABASE_USERNAME: supakon
      DATABASE_PASSWORD: ppap1190
      DATABASE_SSL: "false"
    depends_on:
      - db

volumes:
  pgadmin_data:
